import React,{useMemo,useState} from 'react';
import type { AppState } from '../../shared/types';

export function AccountsPage({state,refresh}:{state:AppState|null;refresh:()=>void}){
  const [name,setName]=useState(''); const [handle,setHandle]=useState('');
  const [platformId,setPlatformId]=useState('xiaohongshu'); const [profileId,setProfileId]=useState('');
  const freeProfiles=useMemo(()=>state?.profiles.filter(p=>!p.accountId)||[],[state?.profiles]);
  async function addProfile(){const n=window.prompt('Profile name','New Creator Profile');if(!n)return;await window.creatorOS.profile.create({name:n,platform:state?.platforms.find(p=>p.id===platformId)?.key});refresh();}
  async function addAccount(){if(!name.trim())return;await window.creatorOS.account.create({name,handle,platformId,browserProfileId:profileId||undefined});setName('');setHandle('');setProfileId('');refresh();}
  return <div className="page"><h1>Accounts & Profiles</h1><p className="muted">Each social account can bind to a persistent browser profile. The login state lives in that profile, not in the Agent chat.</p><div className="content-grid"><section className="panel"><h2>New account</h2><select className="field" value={platformId} onChange={e=>setPlatformId(e.target.value)}>{state?.platforms.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><input className="field" placeholder="Account name" value={name} onChange={e=>setName(e.target.value)}/><input className="field" placeholder="Handle (optional)" value={handle} onChange={e=>setHandle(e.target.value)}/><div className="row"><select className="field" value={profileId} onChange={e=>setProfileId(e.target.value)}><option value="">No profile yet</option>{freeProfiles.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><button onClick={addProfile}>＋ Profile</button></div><button className="primary" onClick={addAccount}>Create account</button></section><section className="panel"><h2>Managed accounts</h2>{state?.accounts.length?state.accounts.map(a=>{const platform=state.platforms.find(p=>p.id===a.platformId);const profile=state.profiles.find(p=>p.id===a.browserProfileId);return <article className="content-item" key={a.id}><div><b>{a.name}</b><p>{platform?.name??a.platformId}{a.handle?` · ${a.handle}`:''}</p></div><span className="pill">{profile?.name??'No Profile'}</span></article>}):<p className="muted">No accounts yet.</p>}</section></div></div>;
}
